### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by aschoerg** [tjeerdnet/CAMT053Parser#1]
Hi,

Thank you for providing a camt implementation!

Could you please add a license so others & I know if they may use your implementation under which conditions?

Thank you in advance,
Alex

**Comment by tjeerdnet** [comment]
Hello aschoerg,

Sorry for my late reply. I added a MIT license file to the project to make clear under what conditions the project is allowed to be used.

**Comment by aschoerg** [comment]
Thank you @tjeerdnet!
